table 'Source Snapshot'
	lineageTag: 7235eeae-6feb-4547-acb8-60f8c719ae7a

	column dataset
		dataType: string
		lineageTag: d9ddcaa4-37bb-466d-91fd-313123d9c2a3
		summarizeBy: none
		sourceColumn: dataset

		annotation SummarizationSetBy = Automatic

	column source_url
		dataType: string
		lineageTag: b7d9b463-51d4-425c-bc32-46163bd88c11
		summarizeBy: none
		sourceColumn: source_url

		annotation SummarizationSetBy = Automatic

	column retrieved_at
		dataType: string
		lineageTag: 8bb18232-2b59-45ef-b97a-06a4d8350a98
		summarizeBy: none
		sourceColumn: retrieved_at

		annotation SummarizationSetBy = Automatic

	column row_count
		dataType: int64
		lineageTag: 581e6aed-a956-4d14-9eb3-0b08377e7545
		summarizeBy: none
		sourceColumn: row_count

		annotation SummarizationSetBy = Automatic

	column sha256
		dataType: string
		lineageTag: e380540c-62ba-40fc-b503-24e4707aac80
		summarizeBy: none
		sourceColumn: sha256

		annotation SummarizationSetBy = Automatic

	partition 'Source Snapshot Import' = m
		mode: import
		source =
				let
				    CsvPath = ProjectRoot & "\\outputs\\source_snapshot.csv",
				    Source = Csv.Document(File.Contents(CsvPath),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted,{{"source_name", "dataset"}, {"retrieved_at_utc", "retrieved_at"}, {"rows", "row_count"}}),
				    Typed = Table.TransformColumnTypes(Renamed,{{"dataset", type text}, {"source_url", type text}, {"retrieved_at", type text}, {"row_count", Int64.Type}, {"sha256", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
